In [52]:
import numpy as np
import pandas as pd
import numpy.linalg as lin

In [53]:
# 문제해결에 필요한 Matrix 형성
file = open("../프로그래밍 최종과제/2014170806.txt", "r")
input_data = file.read()
matrix = input_data.split("\n\n")
file.close()
matrix

['Maximize\t7\t8\t2\t10\t2\t7\t2',
 '1\t6\t8\t1\t7\t6\t3\t=\t1\n1\t4\t8\t4\t3\t1\t1\t>=\t7\n8\t6\t9\t7\t10\t9\t5\t=\t1\n1\t1\t5\t2\t10\t6\t2\t<=\t10',
 'Generals\nx0,x1,x2,x3,x4,x5,x6']

In [54]:
matrix2 = matrix[1].split("\n")
list_a=[]
for i in range(len(matrix2)):
    list_a.append(matrix2[i].split("\t"))
list_a

[['1', '6', '8', '1', '7', '6', '3', '=', '1'],
 ['1', '4', '8', '4', '3', '1', '1', '>=', '7'],
 ['8', '6', '9', '7', '10', '9', '5', '=', '1'],
 ['1', '1', '5', '2', '10', '6', '2', '<=', '10']]

In [55]:
A = []
for i in range(len(list_a)):
    list_a[i][len(list_a[i])-1] = int(list_a[i][len(list_a[i])-1])
    for j in range(len(list_a[i])-2):
        list_a[i][j] = int(list_a[i][j])    

list_a

[[1, 6, 8, 1, 7, 6, 3, '=', 1],
 [1, 4, 8, 4, 3, 1, 1, '>=', 7],
 [8, 6, 9, 7, 10, 9, 5, '=', 1],
 [1, 1, 5, 2, 10, 6, 2, '<=', 10]]

In [56]:
matrix1 = matrix[0].split("\t")
cT = matrix1[1:]
for i in range(len(cT)):
    cT[i] = int(cT[i])

if matrix1[0]=='Minimize':
    for i in range(len(cT)):
        cT[i] = -cT[i]
        matrix[0]='Max'


for i in range(3):
    cT.append(-100)

for i in range(2):
    cT.append(0)

print('cT=',cT)

cT= [7, 8, 2, 10, 2, 7, 2, -100, -100, -100, 0, 0]


In [57]:
for i in range(len(list_a)) :
    if list_a[i][-2]=='>='or'=':
        for j in range(7,10):
            if j==i+7 :
                list_a[i].insert(j,1)
            else :
                list_a[i].insert(j,0)
    else :
        list_a[i].extend([0,0,0])
list_a

[[1, 6, 8, 1, 7, 6, 3, 1, 0, 0, '=', 1],
 [1, 4, 8, 4, 3, 1, 1, 0, 1, 0, '>=', 7],
 [8, 6, 9, 7, 10, 9, 5, 0, 0, 1, '=', 1],
 [1, 1, 5, 2, 10, 6, 2, 0, 0, 0, '<=', 10]]

In [58]:
for i in range(len(list_a)) :
    if list_a[i][-2]=='=':
        list_a[i].insert(10,0)
        list_a[i].insert(11,0)
        
    if list_a[i][-2]=='>=':
        list_a[i].insert(10,-1)
        list_a[i].insert(11,0)
    
    if list_a[i][-2]=='<=':
        list_a[i].insert(10,0)
        list_a[i].insert(11,1)
list_a

[[1, 6, 8, 1, 7, 6, 3, 1, 0, 0, 0, 0, '=', 1],
 [1, 4, 8, 4, 3, 1, 1, 0, 1, 0, -1, 0, '>=', 7],
 [8, 6, 9, 7, 10, 9, 5, 0, 0, 1, 0, 0, '=', 1],
 [1, 1, 5, 2, 10, 6, 2, 0, 0, 0, 0, 1, '<=', 10]]

In [59]:
A=[]

for i in range(len(list_a)):
    A.append(list_a[i][:len(list_a[i])-2])
print('A=',A)

A= [[1, 6, 8, 1, 7, 6, 3, 1, 0, 0, 0, 0], [1, 4, 8, 4, 3, 1, 1, 0, 1, 0, -1, 0], [8, 6, 9, 7, 10, 9, 5, 0, 0, 1, 0, 0], [1, 1, 5, 2, 10, 6, 2, 0, 0, 0, 0, 1]]


In [60]:
b=[]
for i in range(len(list_a)):
    b.append(list_a[i][-1])
print('b=',b)

b= [1, 7, 1, 10]


In [61]:
x=[['x0'],['x1'],['x2'],['x3'],['x4'],['x5'],['x6'],['a1'],['a2'],['a3'],['s1'],['s2']]
print('x=',x)

x= [['x0'], ['x1'], ['x2'], ['x3'], ['x4'], ['x5'], ['x6'], ['a1'], ['a2'], ['a3'], ['s1'], ['s2']]


In [62]:
print(matrix1[0])
print('cT=',cT)
print('A=',A)
print('b=',b)
print('x=',x)

Maximize
cT= [7, 8, 2, 10, 2, 7, 2, -100, -100, -100, 0, 0]
A= [[1, 6, 8, 1, 7, 6, 3, 1, 0, 0, 0, 0], [1, 4, 8, 4, 3, 1, 1, 0, 1, 0, -1, 0], [8, 6, 9, 7, 10, 9, 5, 0, 0, 1, 0, 0], [1, 1, 5, 2, 10, 6, 2, 0, 0, 0, 0, 1]]
b= [1, 7, 1, 10]
x= [['x0'], ['x1'], ['x2'], ['x3'], ['x4'], ['x5'], ['x6'], ['a1'], ['a2'], ['a3'], ['s1'], ['s2']]


In [63]:
#1 simplex시작
BasicV=[['a1'],['a2'],['a3'],['s2']]


NullV=[['x0'], ['x1'], ['x2'], ['x3'], ['x4'], ['x5'], ['x6'], ['s1']]

x0=0
x1=0
x2=0
x3=0
x4=0
x5=0
x6=0
s1=0
NV=[x0, x1, x2, x3, x4, x5, x6, s1]

In [64]:

#1
B=[]
N=[]
cbT=[]
cnT=[]
Binverse=[]
for j in range(len(BasicV)):
    for i in range(len(x)):
        if x[i]==BasicV[j]:
            B.append([A[0][i],A[1][i],A[2][i],A[3][i]])
            cbT.append(cT[i])

for j in range(len(NullV)):
    for i in range(len(x)):
        if x[i]==NullV[j]:
            N.append([A[0][i],A[1][i],A[2][i],A[3][i]])
            cnT.append(cT[i])

Binverse=lin.inv(B)

print("B=",B)
print("\nBinverse=",Binverse)
print("\nN=",N)
print("\ncbT=",cbT)
print("\ncnT=",cnT)

B= [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]

Binverse= [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

N= [[1, 1, 8, 1], [6, 4, 6, 1], [8, 8, 9, 5], [1, 4, 7, 2], [7, 3, 10, 10], [6, 1, 9, 6], [3, 1, 5, 2], [0, -1, 0, 0]]

cbT= [-100, -100, -100, 0]

cnT= [7, 8, 2, 10, 2, 7, 2, 0]


In [65]:
#1
z=0
xB=[]
xN=[]
xoptimal=[]
for i in range(len(B)):
      xB.append(Binverse[i][0]*b[0]+B[i][1]*b[1]+B[i][2]*b[2]+B[i][3]*b[3])
for i in range(len(xB)):
    xB[i]=int(xB[i])

    
for i in range(len(N)):
    xN.append(0)
    
for i in range(len(cbT)):
    z+=cbT[i]*xB[i]

for i in range(len(N)):
    xoptimal.append(xN[i])
    
    
for i in range(len(xB)):
    xoptimal.append(xB[i])



    


print("xoptimal=",xoptimal)
print("\nz=",z)

xoptimal= [0, 0, 0, 0, 0, 0, 0, 0, 1, 7, 1, 10]

z= -900


In [66]:
#1
BinV=[[0]*len(Binverse) for i in range(len(N))]

for i in range(len(Binverse)):
    for j in range(len(N)):
        for k in range(len(Binverse[i])):
            BinV[j][i]+=Binverse[k][i]*N[j][k]

for j in range(len(BinV[i])):
    for i in range(len(BinV)): 
        BinV[i][j]=int(BinV[i][j])
BinV

cbtbinvn=[0]*len(cnT)

for i in range(len(BinV)):
    for j in range(len(cbT)):
            cbtbinvn[i]+=cbT[j]*BinV[i][j]
            
cbtbinvn

deltaz=[0]*len(cnT)

for i in range(len(cnT)):
    deltaz[i]=cnT[i]-cbtbinvn[i]

print("delta z=",deltaz)

delta z= [1007, 1608, 2502, 1210, 2002, 1607, 902, -100]


In [67]:
#1
print("Basic Variables=",BasicV)
print("Non Basic Variables=",NullV)
print("Objective Value z=",z)
print("Basic Feasible Solution x=",xoptimal)
print("Delta z=",deltaz)

Basic Variables= [['a1'], ['a2'], ['a3'], ['s2']]
Non Basic Variables= [['x0'], ['x1'], ['x2'], ['x3'], ['x4'], ['x5'], ['x6'], ['s1']]
Objective Value z= -900
Basic Feasible Solution x= [0, 0, 0, 0, 0, 0, 0, 0, 1, 7, 1, 10]
Delta z= [1007, 1608, 2502, 1210, 2002, 1607, 902, -100]


In [68]:
#1 # Dual infeasible 일때 entering
enterorder= deltaz.index(max(deltaz))
enteringvariable = NullV[enterorder]
enteringvariable

['x2']

In [69]:
#1 #primal infeasible 일때 leaving
primal=[]
variable=[]
for i in range(len(BinV[enterorder])):
    if xB[enterorder]/BinV[enterorder][i] >0:
        primal.append(xB[enterorder]/BinV[enterorder][i])
        variable.append(BasicV[i])

primalsimplex=primal.index(min(primal))
leavingvariable=variable[primalsimplex]
leavingvariable

['a3']

In [70]:
print("entering variable =",enteringvariable)
print("leaving variable =",leavingvariable)

entering variable = ['x2']
leaving variable = ['a3']


In [71]:
#2
BasicV=[['a1'],['a2'],['x2'],['s2']]


NullV=[['x0'], ['x1'], ['a3'], ['x3'], ['x4'], ['x5'], ['x6'], ['s1']]

x0=0
x1=0
a3=0
x3=0
x4=0
x5=0
x6=0
s1=0
NV=[x0, x1, a3, x3, x4, x5, x6, s1]


In [72]:
#2
B=[]
N=[]
cbT=[]
cnT=[]
Binverse=[]
for j in range(len(BasicV)):
    for i in range(len(x)):
        if x[i]==BasicV[j]:
            B.append([A[0][i],A[1][i],A[2][i],A[3][i]])
            cbT.append(cT[i])

for j in range(len(NullV)):
    for i in range(len(x)):
        if x[i]==NullV[j]:
            N.append([A[0][i],A[1][i],A[2][i],A[3][i]])
            cnT.append(cT[i])

Binverse=lin.inv(B)

print("B=",B)
print("\nBinverse=",Binverse)
print("\nN=",N)
print("\ncbT=",cbT)
print("\ncnT=",cnT)

B= [[1, 0, 0, 0], [0, 1, 0, 0], [8, 8, 9, 5], [0, 0, 0, 1]]

Binverse= [[ 1.00000000e+00  0.00000000e+00  6.93889390e-18  2.77555756e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.88888889e-01 -8.88888889e-01  1.11111111e-01 -5.55555556e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]

N= [[1, 1, 8, 1], [6, 4, 6, 1], [0, 0, 1, 0], [1, 4, 7, 2], [7, 3, 10, 10], [6, 1, 9, 6], [3, 1, 5, 2], [0, -1, 0, 0]]

cbT= [-100, -100, 2, 0]

cnT= [7, 8, -100, 10, 2, 7, 2, 0]


In [73]:
#2
z=0
xB=[]
xN=[]
xoptimal=[]
for i in range(len(B)):
      xB.append(Binverse[i][0]*b[0]+B[i][1]*b[1]+B[i][2]*b[2]+B[i][3]*b[3])
for i in range(len(xB)):
    xB[i]=int(xB[i])

    
for i in range(len(N)):
    xN.append(0)
    
for i in range(len(cbT)):
    z+=cbT[i]*xB[i]

for i in range(len(N)):
    xoptimal.append(xN[i])
    
    
for i in range(len(xB)):
    xoptimal.append(xB[i])



    


print("xoptimal=",xoptimal)
print("\nz=",z)

xoptimal= [0, 0, 0, 0, 0, 0, 0, 0, 1, 7, 114, 10]

z= -572


In [74]:
#2
BinV=[[0]*len(Binverse) for i in range(len(N))]

for i in range(len(Binverse)):
    for j in range(len(N)):
        for k in range(len(Binverse[i])):
            BinV[j][i]+=Binverse[k][i]*N[j][k]

for j in range(len(BinV[i])):
    for i in range(len(BinV)): 
        BinV[i][j]=int(BinV[i][j])
BinV

cbtbinvn=[0]*len(cnT)

for i in range(len(BinV)):
    for j in range(len(cbT)):
            cbtbinvn[i]+=cbT[j]*BinV[i][j]
            
cbtbinvn

deltaz=[0]*len(cnT)

for i in range(len(cnT)):
    deltaz[i]=cnT[i]-cbtbinvn[i]

deltaz
#dual feasible

[-1193, -92, -100, -690, -600, -895, -398, -100]

In [75]:
#2
print("Basic Variables=",BasicV,"=",xB)
print("Non Basic Variables=",NullV)
print("Objective Value z=",z)
print("Delta z=",deltaz)

Basic Variables= [['a1'], ['a2'], ['x2'], ['s2']] = [1, 7, 114, 10]
Non Basic Variables= [['x0'], ['x1'], ['a3'], ['x3'], ['x4'], ['x5'], ['x6'], ['s1']]
Objective Value z= -572
Delta z= [-1193, -92, -100, -690, -600, -895, -398, -100]
