In [1]:
import numpy as np

In [16]:
list1= (3,2,5,0,0,0)
list2=([1,2,1,1,0,0],[3,0,2,0,1,0],[1,4,0,0,0,1])
list3=([430],[460],[420])

In [19]:
a=np.matrix(list1)
b=np.matrix(list2)
c=np.matrix(list3)

print(a)
print(b)
print(b.T)
print(b[0],b[1],b[2])
print(c)

[[3 2 5 0 0 0]]
[[1 2 1 1 0 0]
 [3 0 2 0 1 0]
 [1 4 0 0 0 1]]
[[1 3 1]
 [2 0 4]
 [1 2 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 2 1 1 0 0]] [[3 0 2 0 1 0]] [[1 4 0 0 0 1]]
[[430]
 [460]
 [420]]
