In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import numpy as np
%matplotlib inline
import random
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import scipy as sp
import sklearn as skl

# NN.MODULE

In [6]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 5000, 1000, 100, 10

torch.manual_seed(0)
# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Use the nn package to define our model as a sequence of layers. nn.Sequential
# is a Module which contains other Modules, and applies them in sequence to
# produce its output. Each Linear Module computes output from input using a
# linear function, and holds internal Tensors for its weight and bias.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# The nn package also contains definitions of popular loss functions; in this
# case we will use Mean Squared Error (MSE) as our loss function.
loss_fn = torch.nn.MSELoss(reduction='mean')

learning_rate = 1e-4
for t in range(10000):
    # Forward pass: compute predicted y by passing x to the model. Module objects
    # override the __call__ operator so you can call them like functions. When
    # doing so you pass a Tensor of input data to the Module and it produces
    # a Tensor of output data.
    y_pred = model(x)

    # Compute and print loss. We pass Tensors containing the predicted and true
    # values of y, and the loss function returns a Tensor containing the
    # loss.
    loss = loss_fn(y_pred, y)
    if (t+1) % 100 == 0:
        print(f't={t+1}, loss={loss.item()}')

    # Zero the gradients before running the backward pass.
    model.zero_grad()

    # Backward pass: compute gradient of the loss with respect to all the learnable
    # parameters of the model. Internally, the parameters of each Module are stored
    # in Tensors with requires_grad=True, so this call will compute gradients for
    # all learnable parameters in the model.
    loss.backward()

    # Update the weights using gradient descent. Each parameter is a Tensor, so
    # we can access its gradients like we did before.
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad

t=100, loss=1.04984450340271
t=200, loss=1.049482822418213
t=300, loss=1.0491256713867188
t=400, loss=1.0487738847732544
t=500, loss=1.048426628112793
t=600, loss=1.0480839014053345
t=700, loss=1.0477454662322998
t=800, loss=1.047411561012268
t=900, loss=1.0470815896987915
t=1000, loss=1.0467565059661865
t=1100, loss=1.046434760093689
t=1200, loss=1.0461171865463257
t=1300, loss=1.0458033084869385
t=1400, loss=1.0454931259155273
t=1500, loss=1.0451871156692505
t=1600, loss=1.0448840856552124
t=1700, loss=1.0445846319198608
t=1800, loss=1.0442886352539062
t=1900, loss=1.043995976448059
t=2000, loss=1.0437062978744507
t=2100, loss=1.0434197187423706
t=2200, loss=1.0431368350982666
t=2300, loss=1.0428564548492432
t=2400, loss=1.0425785779953003
t=2500, loss=1.0423040390014648
t=2600, loss=1.042032241821289
t=2700, loss=1.0417633056640625
t=2800, loss=1.0414966344833374
t=2900, loss=1.0412324666976929
t=3000, loss=1.0409709215164185
t=3100, loss=1.0407118797302246
t=3200, loss=1.0404551029

# nn.module, optimizer

In [11]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 1000, 1000, 100, 10
torch.manual_seed(0)
# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Use the nn package to define our model and loss function.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)
loss_fn = torch.nn.MSELoss(reduction='sum')

# Use the optim package to define an Optimizer that will update the weights of
# the model for us. Here we will use Adam; the optim package contains many other
# optimization algorithms. The first argument to the Adam constructor tells the
# optimizer which Tensors it should update.
learning_rate = 1e-3
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
for t in range(10000):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute and print loss.
    loss = loss_fn(y_pred, y)
    if (t+1) % 100 == 0:
        print(f't={t+1}, loss={loss.item()}')


    # Before the backward pass, use the optimizer object to zero all of the
    # gradients for the variables it will update (which are the learnable
    # weights of the model). This is because by default, gradients are
    # accumulated in buffers( i.e, not overwritten) whenever .backward()
    # is called. Checkout docs of torch.autograd.backward for more details.
    optimizer.zero_grad()

    # Backward pass: compute gradient of the loss with respect to model
    # parameters
    loss.backward()

    # Calling the step function on an Optimizer makes an update to its
    # parameters
    optimizer.step()


t=100, loss=0.5628461241722107
t=200, loss=0.0005767779657617211
t=300, loss=1.0997649013688715e-07
t=400, loss=2.429960677119425e-10
t=500, loss=2.6687119181190155e-10
t=600, loss=2.979830826532748e-10
t=700, loss=3.1671854028303414e-10
t=800, loss=3.5331670922289504e-10
t=900, loss=3.820583294178448e-10
t=1000, loss=4.1128750405405867e-10
t=1100, loss=4.2247250142679604e-10
t=1200, loss=4.727888081035303e-10
t=1300, loss=4.909447293144353e-10
t=1400, loss=5.465058960929525e-10
t=1500, loss=5.610036324377177e-10
t=1600, loss=5.825419036042945e-10
t=1700, loss=6.2302479841847e-10
t=1800, loss=6.826547105376335e-10
t=1900, loss=6.797240548195305e-10
t=2000, loss=7.435330684479879e-10
t=2100, loss=7.773088284146468e-10
t=2200, loss=0.2085253745317459
t=2300, loss=4.6196719267754816e-06
t=2400, loss=5.327171311364509e-05
t=2500, loss=0.00019293637888040394
t=2600, loss=0.13435178995132446
t=2700, loss=0.0030235524754971266
t=2800, loss=0.013658409006893635
t=2900, loss=0.00018514838302507

# custom nn.module

In [14]:
class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate two nn.Linear modules and assign them as
        member variables.
        """
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred


# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 100, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the two
# nn.Linear modules which are members of the model.
criterion = torch.nn.MSELoss(reduction='mean')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)
for t in range(1000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if (t+1) % 100 == 0:
        print(f't={t+1}, loss={loss.item()}')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

t=100, loss=0.9667409062385559
t=200, loss=0.9596579074859619
t=300, loss=0.9526708126068115
t=400, loss=0.9457768797874451
t=500, loss=0.9389777779579163
t=600, loss=0.9322686195373535
t=700, loss=0.9256381392478943
t=800, loss=0.9190851449966431
t=900, loss=0.9126030802726746
t=1000, loss=0.9061959385871887


# PyTorch: Control Flow + Weight Sharing
As an example of dynamic graphs and weight sharing, we implement a very strange model: a fully-connected ReLU network that on each forward pass chooses a random number between 1 and 4 and uses that many hidden layers, reusing the same weights multiple times to compute the innermost hidden layers.

For this model we can use normal Python flow control to implement the loop, and we can implement weight sharing among the innermost layers by simply reusing the same Module multiple times when defining the forward pass.

We can easily implement this model as a Module subclass:

In [6]:
import random


class DynamicNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we construct three nn.Linear instances that we will use
        in the forward pass.
        """
        super(DynamicNet, self).__init__()
        self.input_linear = torch.nn.Linear(D_in, H)
        self.middle_linear = torch.nn.Linear(H, H)
        self.output_linear = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        For the forward pass of the model, we randomly choose either 0, 1, 2, or 3
        and reuse the middle_linear Module that many times to compute hidden layer
        representations.

        Since each forward pass builds a dynamic computation graph, we can use normal
        Python control-flow operators like loops or conditional statements when
        defining the forward pass of the model.

        Here we also see that it is perfectly safe to reuse the same Module many
        times when defining a computational graph. This is a big improvement from Lua
        Torch, where each Module could be used only once.
        """
        h_relu = self.input_linear(x).clamp(min=0)
        for _ in range(random.randint(0, 3)):
            h_relu = self.middle_linear(h_relu).clamp(min=0)
        y_pred = self.output_linear(h_relu)
        return y_pred


# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Construct our model by instantiating the class defined above
model = DynamicNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. Training this strange model with
# vanilla stochastic gradient descent is tough, so we use momentum
criterion = torch.nn.MSELoss(reduction='mean')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4, momentum=0.9)
for t in range(1000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if (t+1) % 100 == 0:
       print(f't={t+1}, loss={loss.item()}')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


t=100, loss=0.9823983311653137
t=200, loss=0.9734675288200378
t=300, loss=0.9661868214607239
t=400, loss=0.9575799703598022
t=500, loss=0.9506648182868958
t=600, loss=0.870894730091095
t=700, loss=0.9611701965332031
t=800, loss=0.9547517895698547
t=900, loss=0.9529311060905457
t=1000, loss=0.7741754651069641


In [7]:
torch.manual_seed(0)
a = torch.randn(4)
b= torch.randn(10)
print(a)
print(a.clamp(min=0)) #min 보다 작으면 min 값으로 통일 / min=0으로 두면 relu랑도 같은 역할을 할 수는 있겠구먼
print(b)
print(b.clamp(min=-0.5,max=0.9999)) 


tensor([ 1.5410, -0.2934, -2.1788,  0.5684])
tensor([1.5410, 0.0000, 0.0000, 0.5684])
tensor([-1.0845, -1.3986,  0.4033,  0.8380, -0.7193, -0.4033, -0.5966,  0.1820,
        -0.8567,  1.1006])
tensor([-0.5000, -0.5000,  0.4033,  0.8380, -0.5000, -0.4033, -0.5000,  0.1820,
        -0.5000,  0.9999])
