In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset
import torchvision
import torchvision.transforms as transforms
import numpy as np
%matplotlib inline
import random
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import scipy as sp
import sklearn as skl

In [3]:
>>> # With square kernels and equal stride
>>> x = torch.randn(1,3,8,8)

>>> conv=torch.nn.Conv2d(in_channels=3,out_channels=1,kernel_size=3,stride=2,padding=1)
weight=conv.weight
print(x.shape)
print(weight)
print(conv(x))
print(conv(x).shape)

torch.Size([1, 3, 8, 8])
Parameter containing:
tensor([[[[-0.0271, -0.0592,  0.0965],
          [ 0.0491, -0.0891, -0.0078],
          [-0.0748, -0.1739,  0.1267]],

         [[ 0.0256, -0.0437, -0.0183],
          [ 0.1920,  0.0265,  0.1745],
          [-0.1120, -0.0905,  0.0714]],

         [[-0.0841, -0.1917, -0.0828],
          [ 0.1026,  0.1799,  0.1650],
          [ 0.0976,  0.1532,  0.1068]]]], requires_grad=True)
tensor([[[[-0.3272, -1.3041, -0.8032,  0.7630],
          [ 0.0448, -0.5082, -0.4975,  0.0793],
          [ 0.4740, -0.0879,  1.0316,  0.1724],
          [-0.4809, -0.6931, -0.0475, -0.3629]]]],
       grad_fn=<MkldnnConvolutionBackward>)
torch.Size([1, 1, 4, 4])


In [ ]:
x=torch.nn.functional.pad(x,(0,1,0,1))
print(conv(x).shape)

torch.Size([1, 1, 4, 4])


In [ ]:
x=torch.randn(1,4,8,8)
x=x.view(-1,4*8*8)

linear=torch.nn.Linear(in_features=4*8*8,out_features=8*4*4)
y=linear(x)
y=y.view(1,8,4,4)
print(y)

tensor([[[[ 1.0590,  0.7232, -0.1560, -0.4220],
          [ 0.1505, -0.5897, -0.3813, -0.1130],
          [ 0.4022, -0.2270, -0.0555,  0.1527],
          [-0.2123,  0.1205, -0.0673, -0.2800]],

         [[-0.3319,  0.3321, -0.1590,  0.9011],
          [-0.5998, -0.0914,  0.2232,  0.2487],
          [ 0.2550, -1.0299,  0.1413, -0.0445],
          [ 0.8570, -0.2144, -0.1234,  1.2668]],

         [[ 0.4038,  1.2842, -0.6216, -0.1497],
          [ 0.8361,  1.2243, -0.4883, -0.8381],
          [-0.1818,  0.2070, -0.0639, -0.6632],
          [ 0.0994,  0.2142,  0.5880, -0.6272]],

         [[ 1.0392,  0.5223,  0.7546, -0.0653],
          [ 0.9910,  0.8603,  0.5248,  0.7311],
          [ 0.2720, -0.5542, -0.2709,  0.3904],
          [ 0.2269,  0.3234, -0.0898, -0.4712]],

         [[-0.3863,  0.6426, -0.2590,  0.6142],
          [ 0.1607,  0.1491,  0.6009, -0.4484],
          [-1.0511, -0.5020, -0.1741,  0.4996],
          [-0.6637, -0.5857, -0.1251,  0.5881]],

         [[ 0.1517,  0.4060, -