In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [ ]:
from __future__ import print_function
import torch
import numpy as np


In [ ]:
!pip install cuda

ERROR: Could not find a version that satisfies the requirement cuda (from versions: none)
ERROR: No matching distribution found for cuda


<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [ ]:
torch.manual_seed(0)
x = torch.empty(5, 3) #계속 바뀜
print(x)
y=np.random.rand(5,3)
print(y)
print(type(x))

tensor([[1.7053e-37, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 2.5223e-36]])
[[0.06875022 0.02213544 0.82216261]
 [0.48292556 0.10090894 0.44769137]
 [0.66644064 0.25018326 0.46282834]
 [0.2763262  0.12790008 0.68433205]
 [0.67469786 0.11871962 0.41194907]]
<class 'torch.Tensor'>


Construct a randomly initialized matrix:



In [ ]:

x = torch.empty(5, 3) #계속 바뀜
print(x)
x = torch.rand(5, 3) #0~1사이
print(x)
x = torch.randn(5, 3)
print(x)

tensor([[1.7053e-37, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3788e-14, 1.8369e+28, 1.9433e-19],
        [3.3738e-12, 7.4086e+28, 6.9397e+22],
        [1.7260e+25, 2.2856e+20, 5.0948e-14]])
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])
tensor([[ 0.6035,  0.8110, -0.0451],
        [ 0.8797,  1.0482, -0.0445],
        [-0.7229,  2.8663, -0.5655],
        [ 0.1604, -0.0254,  1.0739],
        [ 2.2628, -0.9175, -0.2251]])


Construct a matrix filled zeros and of dtype long:



In [ ]:
x = torch.zeros(5, 3)#torch.float32
print(x)
x = torch.zeros(5, 3, dtype=torch.short) #torch.int16 또는 torch.short
print(x)
x = torch.zeros(5, 3, dtype=torch.long) #64-bit integer (signed)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [ ]:
x = torch.tensor([5.5, 3])
print(x)
print(x.dtype)

x = torch.tensor([5.5, 3],dtype=torch.short)
print(x)
print(x.dtype)

x = torch.tensor([5.5, 3],dtype=torch.long)
print(x)
print(x.dtype)

x = torch.tensor([5.5, 3],dtype=torch.double)
print(x)
print(x.dtype)

x = torch.tensor([5.5, 3],dtype=torch.half)
print(x)
print(x.dtype)

tensor([5.5000, 3.0000])
torch.float32
tensor([5, 3], dtype=torch.int16)
torch.int16
tensor([5, 3])
torch.int64
tensor([5.5000, 3.0000], dtype=torch.float64)
torch.float64
tensor([5.5000, 3.0000], dtype=torch.float16)
torch.float16


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [ ]:
x = x.new_ones(5, 3, dtype=torch.short)      # new_* methods take in sizes
print(x)

x = x.new_empty(5, 3, dtype=torch.double)
print(x)

x = x.new_zeros(5, 3, dtype=torch.long)
print(x)

x=torch.zeros(5,3)
print(x)




NameError: ignored

In [ ]:
y = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(y)                                      # result has the same size

tensor([[ 2.3466, -1.1088,  1.6254],
        [ 1.2333, -0.1832, -1.3140],
        [-1.6894,  1.2525, -0.5545],
        [ 0.3019,  1.1295,  1.7179],
        [-0.8507, -0.8486, -0.1848]])


Get its size:



In [ ]:
print(y.size()==x.size())
print(y.size())

True
torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations

There are multiple syntaxes for operations. \

In the following example, we will take a look at the addition operation.

Addition: syntax 1



In [ ]:
z = torch.rand(5, 3)
print(z)
print(y + z)

tensor([[0.4910, 0.1235, 0.1143],
        [0.4725, 0.5751, 0.2952],
        [0.7967, 0.1957, 0.9537],
        [0.8426, 0.0784, 0.3756],
        [0.5226, 0.5730, 0.6186]])
tensor([[ 2.8377, -0.9854,  1.7397],
        [ 1.7058,  0.3919, -1.0188],
        [-0.8928,  1.4482,  0.3992],
        [ 1.1446,  1.2079,  2.0935],
        [-0.3282, -0.2757,  0.4338]])


Addition: syntax 2



In [ ]:
print('y=',y)
print('z=',z)
print(torch.add(z, y))
print(torch.mul(z, y))
print(torch.sub(y,z))
print(torch.sub(z,y))

y= tensor([[ 2.3466, -1.1088,  1.6254],
        [ 1.2333, -0.1832, -1.3140],
        [-1.6894,  1.2525, -0.5545],
        [ 0.3019,  1.1295,  1.7179],
        [-0.8507, -0.8486, -0.1848]])
z= tensor([[0.4910, 0.1235, 0.1143],
        [0.4725, 0.5751, 0.2952],
        [0.7967, 0.1957, 0.9537],
        [0.8426, 0.0784, 0.3756],
        [0.5226, 0.5730, 0.6186]])
tensor([[ 2.8377, -0.9854,  1.7397],
        [ 1.7058,  0.3919, -1.0188],
        [-0.8928,  1.4482,  0.3992],
        [ 1.1446,  1.2079,  2.0935],
        [-0.3282, -0.2757,  0.4338]])
tensor([[ 1.1522, -0.1369,  0.1858],
        [ 0.5827, -0.1053, -0.3879],
        [-1.3460,  0.2452, -0.5288],
        [ 0.2544,  0.0885,  0.6452],
        [-0.4446, -0.4862, -0.1143]])
tensor([[ 1.8556, -1.2323,  1.5110],
        [ 0.7609, -0.7583, -1.6093],
        [-2.4861,  1.0568, -1.5082],
        [-0.5407,  1.0511,  1.3423],
        [-1.3733, -1.4216, -0.8034]])
tensor([[-1.8556,  1.2323, -1.5110],
        [-0.7609,  0.7583,  1.6093],
     

Addition: providing an output tensor as argument



In [ ]:
result = torch.rand(5, 3)
print('result=',result)

torch.add(x, y)
print(result)

torch.add(x, y, out=result)
print(result)

result[1,1]

result= tensor([[0.5537, 0.3953, 0.8571],
        [0.6396, 0.7403, 0.6766],
        [0.3798, 0.3948, 0.0880],
        [0.7709, 0.8970, 0.8421],
        [0.1473, 0.5223, 0.1475]])
tensor([[0.5537, 0.3953, 0.8571],
        [0.6396, 0.7403, 0.6766],
        [0.3798, 0.3948, 0.0880],
        [0.7709, 0.8970, 0.8421],
        [0.1473, 0.5223, 0.1475]])
tensor([[ 2.3466, -1.1088,  1.6254],
        [ 1.2333, -0.1832, -1.3140],
        [-1.6894,  1.2525, -0.5545],
        [ 0.3019,  1.1295,  1.7179],
        [-0.8507, -0.8486, -0.1848]])


tensor(-0.1832)

Addition: in-place



In [ ]:
# adds x to y
y.add_(z)
print(y)

tensor([[ 2.8377, -0.9854,  1.7397],
        [ 1.7058,  0.3919, -1.0188],
        [-0.8928,  1.4482,  0.3992],
        [ 1.1446,  1.2079,  2.0935],
        [-0.3282, -0.2757,  0.4338]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [ ]:
x=torch.zeros(5,3,dtype=torch.int32)
print(x)
print(y)
print(z.copy_(y)) #z를 y값으로 복사하는것임
print(z) # 그럼 z가 y로 변함
print(z.copy_(x))
print(y[:, 0])

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[ 2.8377, -0.9854,  1.7397],
        [ 1.7058,  0.3919, -1.0188],
        [-0.8928,  1.4482,  0.3992],
        [ 1.1446,  1.2079,  2.0935],
        [-0.3282, -0.2757,  0.4338]])
tensor([[ 2.8377, -0.9854,  1.7397],
        [ 1.7058,  0.3919, -1.0188],
        [-0.8928,  1.4482,  0.3992],
        [ 1.1446,  1.2079,  2.0935],
        [-0.3282, -0.2757,  0.4338]])
tensor([[ 2.8377, -0.9854,  1.7397],
        [ 1.7058,  0.3919, -1.0188],
        [-0.8928,  1.4482,  0.3992],
        [ 1.1446,  1.2079,  2.0935],
        [-0.3282, -0.2757,  0.4338]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([ 2.8377,  1.7058, -0.8928,  1.1446, -0.3282])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [ ]:
x = torch.randn(12)
print(x,x.size())
y = x.view(1,12)
print(y,y.size())
y = x.view(2,6)
print(y,y.size())
y = x.view(3,4)
print(y,y.size())
y = x.view(4,3)
print(y,y.size())
y = x.view(6,2)
print(y,y.size())

z = x.view(-1, 6)  # the size -1 is inferred from other dimensions
print(z)
print(x.size(), y.size(), z.size())

tensor([ 0.1781,  0.3893,  1.4593,  1.3651, -0.9279,  0.4106,  0.5223,  0.6819,
         0.3309,  0.8108,  0.8100,  1.6725]) torch.Size([12])
tensor([[ 0.1781,  0.3893,  1.4593,  1.3651, -0.9279,  0.4106,  0.5223,  0.6819,
          0.3309,  0.8108,  0.8100,  1.6725]]) torch.Size([1, 12])
tensor([[ 0.1781,  0.3893,  1.4593,  1.3651, -0.9279,  0.4106],
        [ 0.5223,  0.6819,  0.3309,  0.8108,  0.8100,  1.6725]]) torch.Size([2, 6])
tensor([[ 0.1781,  0.3893,  1.4593,  1.3651],
        [-0.9279,  0.4106,  0.5223,  0.6819],
        [ 0.3309,  0.8108,  0.8100,  1.6725]]) torch.Size([3, 4])
tensor([[ 0.1781,  0.3893,  1.4593],
        [ 1.3651, -0.9279,  0.4106],
        [ 0.5223,  0.6819,  0.3309],
        [ 0.8108,  0.8100,  1.6725]]) torch.Size([4, 3])
tensor([[ 0.1781,  0.3893],
        [ 1.4593,  1.3651],
        [-0.9279,  0.4106],
        [ 0.5223,  0.6819],
        [ 0.3309,  0.8108],
        [ 0.8100,  1.6725]]) torch.Size([6, 2])
tensor([[ 0.1781,  0.3893,  1.4593,  1.3651, -0.

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5358])
-0.535823404788971


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [ ]:
a = torch.ones(5,dtype=torch.long)
print(a,type(a),a.size())

tensor([1, 1, 1, 1, 1]) <class 'torch.Tensor'> torch.Size([5])


In [ ]:
b = a.numpy()
print(b,type(b),b.size)

[1 1 1 1 1] <class 'numpy.ndarray'> 5


See how the numpy array changed in value.



In [ ]:
a.add_(1)
print(a)
print(b) #b도 같이 저장 되어서 반영되네 십탱구리

tensor([2, 2, 2, 2, 2])
[2 2 2 2 2]


Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically



In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(b,type(b))
np.add(a, 1, out=a)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
